spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: 12345
#    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: pass
    concurrency: 1
    exchanges:
      trader: trader.follow.exchange
    routing-keys:
      start: "start"
      stop: "stop"
    queues:
      startQueue: "trader.follow.start.queue"
      stopQueue: "trader.follow.stop.queue"

  flyway:
    enabled: true
    username: postgres
    password: 12345
#    locations: classpath:db.migration
    baselineOnMigrate: true

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9897

rpc:
  web:
    client: "https://mainnet.helius-rpc.com/?api-key=aa61fddb-a509-48d4-998b-7ae0b0ae5319"
    timeout:
      seconds: 15

solana:
  value: "So11111111111111111111111111111111111111112"
  web:
    address: "wss://api.mainnet-beta.solana.com"
    timeout:
      seconds: 20

raydium:
  address: "So11111111111111111111111111111111111111112"
  lpv4: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"

logging:
  level:
    org.springframework.web: INFO
    org.springframework.core.env: DEBUG
    com.copy.trader: INFO
    org.flywaydb: INFO