spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: 12345
#    driver-class-name: org.postgresql.Driver
  flyway:
    username: postgres
    password: 12345
    enabled: true
#    locations: classpath:db.migration
    baselineOnMigrate: true

  jpa:
    hibernate:
      ddl-auto: update

rpc:
  web:
    client: "https://mainnet.helius-rpc.com/?api-key=aa61fddb-a509-48d4-998b-7ae0b0ae5319"
    timeout:
      seconds: 15

solana:
  value: "So11111111111111111111111111111111111111112"
  web:
    address: "wss://api.mainnet-beta.solana.com"
    timeout:
      seconds: 20

raydium:
  address: "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1"
  lpv4: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"

logging:
  level:
    org.springframework.web: INFO
    org.springframework.core.env: DEBUG
    com.copy.trade: INFO
    org.flywaydb: DEBUG