version: '3.3'

services:
  postgresql:
    image: postgres
    container_name: postgres-trader
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: 12345
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-trader
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbit_config.json:/opt/config/rabbit_config.json
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_management load_definitions "/opt/config/rabbit_config.json"