spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: pass
    concurrency: 1
    async-template:
      converter-future:
        timeout:
          seconds: 20
    exchanges:
      trader: trader.exchange
    routing-keys:
      default: "#"

server:
  port: 8182

bot:
  token: 1748682168:AAGmDaWc_8xyCeEoS8BfaVban_Ng7fKECfU
  username: sniper
  session:
    maxAuthSessions: 20
    maxFollowSessions: 30
    maxSubscriptionSessions: 10
rpc:
  web:
    client: "https://mainnet.helius-rpc.com/?api-key=aa61fddb-a509-48d4-998b-7ae0b0ae5319"

logging:
  level:
    org.springframework.web: INFO
    org.springframework.core.env: DEBUG
    com.copy.telegram: INFO
    org.flywaydb: DEBUG